### ISSUE TITLE
Support primaryKey

### ISSUE THREAD

**Issue by rufuspollock** [frictionlessdata/tableschema-sql-py#1]
If a primaryKey is set in the JTS use it.

Maybe we want a flag where we ignore it and create our own auto increment but set that the primaryKey field to unique (?)

**Comment by pudo** [comment]
+1 on the latter approach, I'm really skeptical toward treating source data as a trustworthy thing, but we should support the PK annotation from JTS. Also set an index etc.

**Comment by rufuspollock** [comment]
@pudo can we support both options and perhaps default to the latter? Can we get this support in?

**Comment by roll** [comment]
DONE in updated version
