### ISSUE TITLE
Support all Table Schema constraints

### ISSUE THREAD

**Issue by roll** [frictionlessdata/tableschema-sql-py#11]
Requires #27 

Initial implementation restrictions:
- [x] `fields[].constraints.unique` is not supported
- [x] `fields[].constraints.minLength` is not supported
- [ ] `fields[].constraints.maxLength` is not supported
- [x] `fields[].constraints.minimum` is not supported
- [x] `fields[].constraints.maximum` is not supported
- [x] `fields[].constraints.pattern` is not supported
- [x] `fields[].constraints.enum` is not supported

Reference: 
- https://frictionlessdata.io/specs/table-schema/#constraints
- https://docs.sqlalchemy.org/en/13/core/constraints.html#check-constraint

**Comment by zaneselvans** [comment]
Hey @roll, @cmgosnell and I were noticing that these constraints aren't getting integrated into the database schema when we load the PUDL datapackages into SQLite, and we do depend especially on ENUM to make sure that the contents are valid... My guess right now is that goodtables won't be fast enough to practically validate our larger datasets, so we were imagining that actually loading the data into the database would be checking a lot of the structural / constraint issues. But for that to work I think we would need to get these constraints into the database schema. Might we able to add this issue to the catalyst-pilot work?

**Comment by roll** [comment]
Thanks @zaneselvans. Added it - https://github.com/frictionlessdata/pilot-catalyst/issues/17
