### ISSUE TITLE
Consider whether we support full Tabular Data Package loading

### ISSUE THREAD

**Issue by rufuspollock** [frictionlessdata/tableschema-sql-py#2]
With full Tabular Data Package we would have all the resource names plus data file paths and could do a complete load including setting table names etc.

Also we would handle foreign keys.

Should this be in this library? If not maybe we want tdp-to-sql as well.

**Comment by rufuspollock** [comment]
I'm increasingly think we at least want to support a full resources list i.e. the resources attribute in Tabular Data Package so you can build all of the tables you need and handle foreignkeys.

**Comment by danfowler** [comment]
I support this. I'd lean toward a separate tdp-sql library.

**Comment by rufuspollock** [comment]
@danfowler ok can we tdp-to-sql then (or since explicit seems better tabular-data-package-to-sql ;-) ...)

**Comment by rufuspollock** [comment]
@pudo / @danfowler how are we doing on this? I'm happy to see it in here first and then moved out or straight up in a separate repo.

/cc @pwalsh

**Comment by danfowler** [comment]
@rgrp I'm working on sorting out foreignkeys support currently. Once that's done, the full load should be trivial, I think.

**Comment by pudo** [comment]
Sounds awesome. I'd be keen to see the separation of the TDP/JTS thing since their complexity seems to differ by an order of magnitude and I think having lean JTS tooling would be a value in itself.

**Comment by pwalsh** [comment]
Definitely agree with @danfowler and @pudo on having TDP/JTS as distinct libs.

**Comment by rufuspollock** [comment]
Great we have a plan @danfowler i'll leave you to boot tabular-data-package-to-sql ;-)

I do note one subtlety: whether you want this library to handle "multiple" tables - strictly this takes you a bit into tabular data package territory but it makes sense if you have foreign keys etc. You also have the point that table naming really comes outside of JTS (it is in the resource descriptor).

**Comment by danfowler** [comment]
@rgrp tabular-data-package-to-sql will handle the loading of TDP resources, setting table names, and joining, but it will depend on jts-sql being at least able to "see" other tables.

**Comment by rufuspollock** [comment]
@danfowler makes perfect sense!

**Comment by pwalsh** [comment]
Yes, in a distinct library that is starting development now: https://github.com/okfn/datapackage-sql-py
