### ISSUE TITLE
Is there a package which only has an abstract model of JTS?

### ISSUE THREAD

**Issue by pudo** [frictionlessdata/tableschema-sql-py#3]
Without any data parsing code etc, just a schema validator and object to reflect it.

**Comment by rufuspollock** [comment]
Not in python - but there should be one. I note there are JSON schemas for JSON Table Schema here:

https://github.com/dataprotocols/schemas

**Comment by pwalsh** [comment]
Hey @pudo 

As @rgrp points out, there is [this JSON Schema for JTS](https://github.com/dataprotocols/schemas/blob/master/json-table-schema.json), it does not cover the whole spec - see [my notes here](https://github.com/dataprotocols/schemas/issues/5). Using this is Python to do what you want is straightforward: use the [Python JSON Schema lib](https://github.com/Julian/jsonschema) with it.

This should definitely replace the validator I coded in [JTSKit](https://github.com/okfn/json-table-schema-py/blob/master/jtskit/ensure.py), so if you want to do a PR for this there please do. This ensures we all use the same validation code (Python and JS libs), and then we need to iterate on this schema to get it up-to-date with recent changes to the spec and some other points I raised in the issue linked to above.

Hope that helps.

**Comment by pudo** [comment]
I understand wrt. the JSON Schema part, I was just looking for something lightweight that implements utility classes like `Schema` and `Field` which also set sensible defaults etc. I guess that's JTSKit, see  #4 for my confusion on that topic.

**Comment by pwalsh** [comment]
This is relevant for https://github.com/okfn/jsontableschema-py and probably more specifically for https://github.com/okfn/jsontableschema-py/issues/34

I'd say any remaining issues about that API should be raised as issues there.

Closing.
