### ISSUE TITLE
Running tests ...

### ISSUE THREAD

**Issue by rufuspollock** [frictionlessdata/tableschema-sql-py#5]
make test fails with

```
make: virtualenv-3.4: No such file or directory
make: *** [pyenv/bin/python] Error 1
```

BTW is this make stuff a replacement for "old-fashioned" nosetests stuff - i was sort of expecting to do:

```
pip install -e .
nosetests tests
```

**Comment by pudo** [comment]
The latter should work perfectly well, I hope, the `Makefile` is just supposed to be decoration. As for the virtualenv thing, perhaps let's go back to just `virtualenv`... I switched to Py3 based on the bug discussed this morning.

**Comment by pwalsh** [comment]
CLOSING. Tests do run.
