### ISSUE TITLE
Update implementation

### ISSUE THREAD

**Issue by pwalsh** [frictionlessdata/tableschema-sql-py#7]
Hey @pudo 

We are going to update this lib using `jsontableschema`, etc., and also implement https://github.com/okfn/datapackage-sql-py for relational table support, etc. It will be a bumpy ride, but we are thinking that most of the API will be modeled on the great work @roll has recently done for BigQuery integration: https://github.com/okfn?utf8=✓&query=bigquery

All work will be done in a new feature branch. If there is serious conflict with your original design here for `jtssql`, LMK and we can discuss, and/or break it out to a new home.

**Comment by pwalsh** [comment]
@pudo are you interested in checking this before we update the lib?

**Comment by pwalsh** [comment]
@pudo I guess not, So I'll merge this at the beginning of next week.

**Comment by roll** [comment]
DONE
