### ISSUE TITLE
Package tableschema-sql for distribution via conda-forge

### ISSUE THREAD

**Issue by zaneselvans** [frictionlessdata/tableschema-sql-py#79]
We want to use `conda-forge` as a primary distribution channel for the [PUDL package](https://github.com/catalyst-cooperative/pudl) (since it depends on a bunch of PyData stuff that can be a pain for folks to build on their own), but this means that our dependencies [also need to be available via conda](https://conda-forge.org/docs/maintainer/adding_pkgs.html#avoid-external-dependencies), and right now `tableschema-sql` is the only thing that will have to be installed via `pip`. Would it be possible to set up a recipe / feedstock on `conda-forge` for `tableschema-sql`?

**Comment by roll** [comment]
Hi @zaneselvans, working on it - https://github.com/conda-forge/staged-recipes/pull/9149

**Comment by roll** [comment]
It's accepted and going to appear as https://anaconda.org/conda-forge/tableschema-sql soon :+1:

**Comment by zaneselvans** [comment]
Hey @roll, I keep checking to see whether this has shown up on `conda-forge` and it doesn't seem like it has yet. Does it typically take this long for something to show up?

**Comment by roll** [comment]
@zaneselvans It seems some error happened in the first place. I've rereleased - https://anaconda.org/conda-forge/tableschema-sql

**Comment by zaneselvans** [comment]
Great! Now it's working.
