### ISSUE TITLE
Improve memory usage

### ISSUE THREAD

**Issue by roll** [frictionlessdata/tableschema-sql-py#8]
- [x] use stream in `Storage.write()` or write by chunks (#29)
- [x] investigate memory usage in `Storage.read()` (possible SQLAlchemy bug)

**Comment by roll** [comment]
@akariv 
Could you please help here with second part of the issue?
Do you experience any problems with `storage.read` method on big datasets?

**Comment by akariv** [comment]
@roll I haven't used that method at all, so I can't comment on its memory performance (I'm using `babbage` that uses SQLA directly to access the DB).

**Comment by roll** [comment]
Thanks! I had problems with it for OpenTrials so I'll do tests to check.
