### ISSUE TITLE
Maintainer / Lead

### ISSUE THREAD

**Issue by pwalsh** [frictionlessdata/tableschema-sql-py#91]
As per https://github.com/frictionlessdata/project/issues/695#issuecomment-911262730

Would be super if @akariv and I could be marked as leads and have maintainer access here, ands also on the pypi package.

**Comment by akariv** [comment]
@roll could you please add akariv and pwalsh as maintainers on https://pypi.org/project/tableschema-sql/ ? 
Thanks!

**Comment by roll** [comment]
@akariv 
Sure, I've sent invites

**Comment by akariv** [comment]
thanks @roll !

**Comment by pwalsh** [comment]
thank you @roll

**Comment by pwalsh** [comment]
@roll just to note that on:

https://pypi.org/project/tableschema/
https://pypi.org/project/datapackage/
https://pypi.org/project/tableschema-sql/

I have **less** permissions than on some others, eg: https://pypi.org/project/tableschema-elasticsearch/

I don't know if that will impact things yet, but I don't seem to have "manage" permissions.

**Comment by roll** [comment]
I've updated this although I think maintainer is also good enough

**Comment by roll** [comment]
DONE
